CREATE TABLE IF NOT EXISTS machines (
    name TEXT NOT NULL PRIMARY KEY,
    hostname TEXT NOT NULL,
    mac TEXT NOT NULL,
    ip TEXT NOT NULL DEFAULT '',
    arch TEXT NOT NULL DEFAULT 'amd64',
    firmware TEXT NOT NULL DEFAULT 'uefi',
    spec TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_machines_mac ON machines (LOWER(mac));

CREATE TABLE IF NOT EXISTS subnets (
    name TEXT NOT NULL PRIMARY KEY,
    cidr TEXT NOT NULL,
    spec TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    username TEXT NOT NULL PRIMARY KEY,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'viewer',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    token TEXT NOT NULL PRIMARY KEY,
    username TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions (expires_at);

CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT NOT NULL PRIMARY KEY,
    machine TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    result TEXT NOT NULL,
    message TEXT NOT NULL DEFAULT '',
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_machine ON audit_events (machine, created_at DESC);

CREATE TABLE IF NOT EXISTS ssh_keys (
    name TEXT NOT NULL PRIMARY KEY,
    public_key TEXT NOT NULL,
    private_key TEXT NOT NULL DEFAULT '',
    comment TEXT NOT NULL DEFAULT '',
    key_type TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hardware_info (
    machine_name TEXT NOT NULL PRIMARY KEY,
    spec TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hypervisors (
    name TEXT NOT NULL PRIMARY KEY,
    spec TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS registration_tokens (
    token TEXT NOT NULL PRIMARY KEY,
    used INTEGER NOT NULL DEFAULT 0,
    used_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_tokens (
    token TEXT NOT NULL PRIMARY KEY,
    hypervisor_name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_agent_tokens_hypervisor ON agent_tokens (hypervisor_name);

CREATE TABLE IF NOT EXISTS virtual_machines (
    name TEXT NOT NULL PRIMARY KEY,
    hypervisor_ref TEXT NOT NULL DEFAULT '',
    spec TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_vms_hypervisor ON virtual_machines (hypervisor_ref);

CREATE TABLE IF NOT EXISTS cloud_init_templates (
    name TEXT NOT NULL PRIMARY KEY,
    user_data TEXT NOT NULL DEFAULT '',
    network_config TEXT NOT NULL DEFAULT '',
    metadata_tmpl TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS os_images (
    name TEXT NOT NULL PRIMARY KEY,
    spec TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dhcp_leases (
    mac TEXT NOT NULL PRIMARY KEY,
    ip TEXT NOT NULL,
    hostname TEXT NOT NULL DEFAULT '',
    pxe_client INTEGER NOT NULL DEFAULT 0,
    leased_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
