package render

import (
	"os"
	"path/filepath"

	"github.com/sugaf1204/gomi/bootenv/internal/spec"
)

func Render(doc spec.Document, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}
	manifestYAML, err := ManifestYAML(doc)
	if err != nil {
		return err
	}
	buildPlanJSON, err := BuildPlanJSON(doc)
	if err != nil {
		return err
	}
	files := map[string]string{
		doc.Spec.PXE.ScriptName: IPXEScript(doc),
		"manifest.yaml":         manifestYAML,
		"build-plan.json":       buildPlanJSON,
		"plan.txt":              PlanText(doc),
		"boot-environment.yaml": mustEmbeddedYAML(doc),
		"README.generated.txt":  generatedReadme(doc),
	}
	for name, contents := range files {
		if err := os.WriteFile(filepath.Join(outputDir, name), []byte(contents), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func mustEmbeddedYAML(doc spec.Document) string {
	out, err := spec.EmbeddedYAML(doc)
	if err != nil {
		panic(err)
	}
	return out
}

func generatedReadme(doc spec.Document) string {
	return "Generated by gomi-bootenv.\n\n" +
		"Build plan:\n" +
		"  build-plan.json\n\n" +
		"Publish the resulting kernel/initramfs/rootfs using manifest.yaml artifact paths:\n" +
		"  " + doc.Spec.PXE.KernelPath + "\n" +
		"  " + doc.Spec.PXE.InitrdPath + "\n" +
		"  " + doc.Spec.PXE.RootFSPath + "\n"
}
