[Distribution]
Distribution=ubuntu
Release=jammy
Architecture=x86-64
Repositories=universe

[Output]
Format=directory
Output=rootfs

[Content]
Bootable=no
Packages=linux-image-generic,initramfs-tools,systemd,systemd-sysv,ca-certificates,curl,jq,dhcpcd5,lshw,curtin,qemu-utils,parted,util-linux,cloud-init,udev
