[Distribution]
Distribution=ubuntu
Release=jammy
Architecture=x86-64
Repositories=universe

[Output]
Format=directory
Output=rootfs

[Content]
Bootable=no
Packages=linux-image-generic-hwe-22.04,initramfs-tools,cloud-initramfs-rooturl,cloud-initramfs-copymods,overlayroot,systemd,systemd-sysv,ca-certificates,curl,jq,dhcpcd5,lshw,curtin,rsync,sudo,qemu-utils,qemu-block-extra,parted,gdisk,util-linux,e2fsprogs,cloud-init,udev
